name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Setup Node.js environment
      uses: actions/setup-node@v4

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Lint
      run: ./build.sh -p Lint
